### ISSUE TITLE
Add section for sample contract language 

### ISSUE THREAD

**Issue by gbinal** [18F/open-source-program#28]

**Comment by gbinal** [comment]
cc @kfogel

**Comment by gbinal** [comment]
https://pages.18f.gov/open-source-program/pages/contract_language

**Comment by kfogel** [comment]
FWIW, I get a 404 for that URL, @gbinal.  (https://pages.18f.gov/open-source-program/pages/contract_language).  However, I see that the file exists at https://github.com/18F/open-source-program/blob/18f-pages/pages/contract_language.md -- is this just a matter of a small delay in automated deployment?

**Comment by gbinal** [comment]
It is, yes.  The webhooks should be working so I'm not sure what's up but will be addressing it in the morning.

**Comment by mbland** [comment]
Fixed. Turns out this was one of the earliest repos that used 18F Pages, and one of the least active. What happened was, the original repo on the server had the `gh-pages` branch checked out, not `18f-pages`. This happened because the repo was created before 18F Pages forced a checkout of the `18f-pages` branch, and its default branch at that time was `gh-pages`.

**Comment by kfogel** [comment]
Ahh, gotcha.  Thanks for explaining.
