### ISSUE TITLE
make FAQ link open in a new tab 

### ISSUE THREAD

**Issue by gbinal** [18F/open-source-program#74]

**Comment by brittag** [comment]
Opening this sidebar link (http://if.io/open-source-program-template/pages/faq) in a new tab could still be confusing for readers, since readers expect sidebar links to be for navigating the project's resources.

Since this link seems to be a personal-ish project that looks like an official project, it's probably less confusing overall to just copy the content (public domain!) into a new page on this project if we like it.

It'd also help to retitle this from "FAQs" (a generic title) to a specific title that hints at what the content is and why readers might want to read it. This set of questions is background/contextual information, so it should be retitled "About Open Source" and moved to the second spot in the sidebar.
